export type CertificatesCopy = ReturnType<typeof en>;

const en = () => ({
  title: "Certificates",
  lede: "Check completion and attendance, issue a verifiable certificate, and revoke it with a recorded reason if needed.",
  eligible: "Ready to issue",
  issued: "Issued",
  revoked: "Revoked",
  student: "Student",
  course: "Course",
  batch: "Batch",
  attendance: "Attendance",
  enrollment: "Enrollment",
  completed: "Completed",
  notCompleted: "Course not marked complete",
  noAttendance: "No attendance recorded",
  belowAttendance: "Attendance below 75%",
  ready: "Eligible",
  issue: "Issue certificate",
  issuedOn: "Issue date",
  grade: "Grade / result (optional)",
  issuing: "Issuing…",
  certNo: "Certificate no.",
  verify: "Public verification",
  print: "Print certificate",
  revoke: "Revoke certificate",
  revokeReason: "Reason for revocation",
  revokePlaceholder: "Example: name correction requested; replacement certificate issued",
  revoking: "Revoking…",
  noCandidates: "No completed enrollments are ready for certificate review yet.",
  noCertificates: "No certificates issued yet.",
  r2Note: "Printable certificate and public verification work now. Private PDF storage will activate when the R2 certificate binding is added later.",
  viewOnly: "You can view certificates. Issue/revoke requires Certificates manage permission.",
  success: { issued: "Certificate issued.", revoked: "Certificate revoked." },
  errors: {
    denied: "You do not have permission for this action.",
    invalid: "Check the certificate details and try again.",
    missing: "That enrollment or certificate could not be found.",
    ineligible: "This enrollment is not certificate-eligible yet. It must be completed with at least 75% attendance.",
    duplicate: "An active certificate already exists for this enrollment.",
    generic: "Could not save the certificate right now. Please try again."
  }
});

const gu = () => ({
  title: "Certificates",
  lede: "Course completion અને attendance ચેક કરો, verify થઈ શકે એવું certificate issue કરો અને જરૂર પડે તો કારણ સાથે revoke કરો.",
  eligible: "Issue કરવા તૈયાર",
  issued: "Issued",
  revoked: "Revoked",
  student: "Student",
  course: "Course",
  batch: "Batch",
  attendance: "હાજરી",
  enrollment: "Enrollment",
  completed: "Complete",
  notCompleted: "Course complete mark નથી",
  noAttendance: "Attendance record નથી",
  belowAttendance: "Attendance 75%થી ઓછી છે",
  ready: "Eligible",
  issue: "Certificate Issue કરો",
  issuedOn: "Issue date",
  grade: "Grade / result (optional)",
  issuing: "Issue થઈ રહ્યું છે…",
  certNo: "Certificate no.",
  verify: "Public verification",
  print: "Certificate Print કરો",
  revoke: "Certificate Revoke કરો",
  revokeReason: "Revoke કરવાનું કારણ",
  revokePlaceholder: "ઉદાહરણ: નામ સુધારવાનું હતું; replacement certificate issue કર્યું",
  revoking: "Revoke થઈ રહ્યું છે…",
  noCandidates: "હજુ certificate review માટે કોઈ completed enrollment તૈયાર નથી.",
  noCertificates: "હજુ કોઈ certificate issue થયું નથી.",
  r2Note: "Print અને public verification અત્યારે કામ કરે છે. Private PDF storage પછી R2 certificate binding ઉમેરતા activate થશે.",
  viewOnly: "તમે certificates જોઈ શકો છો. Issue/revoke માટે Certificates manage permission જોઈએ.",
  success: { issued: "Certificate issue થઈ ગયું.", revoked: "Certificate revoke થઈ ગયું." },
  errors: {
    denied: "આ કામ કરવાની permission નથી.",
    invalid: "Certificate details ચેક કરીને ફરી try કરો.",
    missing: "આ enrollment કે certificate મળ્યું નથી.",
    ineligible: "આ enrollment હજી certificate માટે eligible નથી. Course complete અને ઓછામાં ઓછી 75% attendance જોઈએ.",
    duplicate: "આ enrollment માટે active certificate પહેલેથી છે.",
    generic: "હમણાં certificate save થઈ શક્યું નથી. ફરી try કરો."
  }
});

export function certificatesCopy(locale: "en" | "gu"): CertificatesCopy { return locale === "gu" ? gu() : en(); }
