import type { DesignStatus } from "./design";

export type DesignCopy = ReturnType<typeof en>;

const en = () => ({
  title: "Design Jobs",
  lede: "Keep every digitising, design development, patch or job-work enquiry together — website brief, walk-in, phone or WhatsApp.",
  addJob: "Add design job",
  addJobHint: "For a client who called, messaged or came to the studio. A website brief is not required.",
  client: "Client name",
  company: "Company / brand (optional)",
  phone: "WhatsApp / mobile",
  email: "Email (optional)",
  language: "Preferred language",
  productType: "Product / job type",
  technique: "Technique",
  dimensions: "Size / dimensions",
  quantity: "Quantity",
  colourCount: "Colours",
  fileFormat: "Required file format",
  deadline: "Client deadline",
  details: "Job details",
  detailsPlaceholder: "What has to be made, special instructions, fabric/machine notes, quote details…",
  create: "Save design job",
  creating: "Saving…",
  search: "Search",
  searchPlaceholder: "Client, company, reference or mobile",
  stage: "Stage",
  allStages: "All stages",
  show: "Show",
  clear: "Clear",
  jobsShown: "Jobs shown",
  needsAction: "Needs action",
  dueSoon: "Deadline due",
  empty: "No design jobs match this view.",
  updateStage: "Update job stage",
  stageNote: "Update note",
  stageNotePlaceholder: "Example: quote ₹___ shared on WhatsApp; client asked for one revision",
  saveStage: "Save stage",
  saving: "Saving…",
  history: "Job history",
  files: "Files",
  noFiles: "No files stored for this job.",
  r2Note: "File upload/download will activate with the private R2 binding later. Jobs and status tracking work without files.",
  viewOnly: "You can view design jobs. Adding or updating them requires Design manage permission.",
  statuses: {
    new: "New job",
    review: "Reviewing",
    info_needed: "Need client info",
    quote_prepared: "Quote ready",
    quote_sent: "Quote sent",
    approved: "Approved",
    in_progress: "Work in progress",
    sample_shared: "Sample shared",
    revision: "Revision",
    finalised: "Finalised",
    delivered: "Delivered",
    closed: "Closed"
  } satisfies Record<DesignStatus, string>,
  success: { created: "Design job added.", updated: "Job details updated.", statusChanged: "Job stage updated." },
  errors: { denied: "You do not have permission for this action.", invalid: "Check the details and try again.", missing: "That design job could not be found.", generic: "Could not save this right now. Please try again." }
});

const gu = () => ({
  title: "Design Jobs",
  lede: "Digitising, design development, patch કે job-work — website brief, walk-in, phone કે WhatsAppથી આવેલું દરેક કામ એક જ જગ્યાએ રાખો.",
  addJob: "નવું Design Job ઉમેરો",
  addJobHint: "Client call કરે, WhatsApp કરે કે studio પર આવે ત્યારે અહીં entry કરો. Website brief આવવું જરૂરી નથી.",
  client: "Clientનું નામ",
  company: "Company / Brand (optional)",
  phone: "WhatsApp / Mobile",
  email: "Email (optional)",
  language: "પસંદની ભાષા",
  productType: "Product / Job type",
  technique: "Technique",
  dimensions: "Size / Dimensions",
  quantity: "Quantity",
  colourCount: "Colours",
  fileFormat: "જોઈતો file format",
  deadline: "Client deadline",
  details: "Job details",
  detailsPlaceholder: "શું બનાવવાનું છે, ખાસ instruction, fabric/machine note, quote details…",
  create: "Design Job Save કરો",
  creating: "Save થઈ રહ્યું છે…",
  search: "શોધો",
  searchPlaceholder: "Client, company, reference કે mobile",
  stage: "Stage",
  allStages: "બધા stages",
  show: "બતાવો",
  clear: "સાફ કરો",
  jobsShown: "દેખાતા jobs",
  needsAction: "Action બાકી",
  dueSoon: "Deadline નજીક",
  empty: "આ viewમાં કોઈ design job નથી.",
  updateStage: "Job stage update કરો",
  stageNote: "Update note",
  stageNotePlaceholder: "ઉદાહરણ: quote WhatsApp પર મોકલ્યો; clientએ એક revision કહ્યું",
  saveStage: "Stage Save કરો",
  saving: "Save થઈ રહ્યું છે…",
  history: "Job history",
  files: "Files",
  noFiles: "આ job માટે કોઈ file store નથી.",
  r2Note: "Private R2 binding પછી file upload/download activate થશે. Job અને status tracking files વગર પણ કામ કરે છે.",
  viewOnly: "તમે design jobs જોઈ શકો છો. ઉમેરવા/ફેરફાર માટે Design manage permission જોઈએ.",
  statuses: {
    new: "નવું Job",
    review: "Reviewમાં",
    info_needed: "Clientની info જોઈએ",
    quote_prepared: "Quote તૈયાર",
    quote_sent: "Quote મોકલ્યો",
    approved: "Approved",
    in_progress: "કામ ચાલુ",
    sample_shared: "Sample મોકલ્યો",
    revision: "Revision",
    finalised: "Finalised",
    delivered: "Delivered",
    closed: "Closed"
  } satisfies Record<DesignStatus, string>,
  success: { created: "Design job ઉમેરાઈ ગયું.", updated: "Job details update થઈ.", statusChanged: "Job stage update થઈ." },
  errors: { denied: "આ કામ કરવાની permission નથી.", invalid: "માહિતી ચેક કરીને ફરી try કરો.", missing: "આ design job મળ્યું નથી.", generic: "હમણાં save થઈ શક્યું નથી. ફરી try કરો." }
});

export function designCopy(locale: "en" | "gu"): DesignCopy { return locale === "gu" ? gu() : en(); }
