import type { FeeMethod } from "./fees";
import type { FeeStatus } from "./fee-status";

export type FeesCopy = ReturnType<typeof en>;

const en = () => ({
  title: "Fees",
  lede: "A simple offline ledger for what was agreed, what was received and what is still due. No online payment happens here.",
  search: "Search student",
  searchPlaceholder: "Name, admission no. or mobile",
  all: "All",
  pendingOnly: "Pending only",
  show: "Show",
  filterStatus: "Show students",
  filterAll: "Everyone",
  filterPending: "Pending fees",
  filterOverdue: "Overdue",
  filterPaid: "Paid in full",
  overdueCount: "Overdue students",
  totalAgreed: "Net fees",
  totalReceived: "Received",
  totalPending: "Pending",
  empty: "No enrollments match this view.",
  courseFee: "Agreed course fee",
  discount: "Discount",
  receivedNow: "Received now",
  method: "Received by",
  receiptNo: "Receipt no. (optional)",
  dueDate: "Next due date",
  notes: "Fee note",
  recordPayment: "Record payment",
  paymentHint: "Enter only what you received today. The student’s agreed fee stays unchanged.",
  moreOptions: "More options",
  discountTotal: "Total discount / concession",
  discountHint: "Keep the current amount unless the institute is giving an additional concession. Recorded discounts are never silently reduced.",
  agreementNeeded: "Set this student’s agreed fee before recording a payment.",
  openLedger: "Open full fee ledger",
  admissionSetupTitle: "Fees for this admission",
  admissionSetupHint: "Set this student’s fee agreement now, and record today’s payment if money was received. Leave the agreement fields blank to use the course default.",
  courseDefaultNote: "Course defaults are shown when available. Changing these values affects this student only.",
  save: "Record payment",
  saving: "Saving…",
  paid: "Paid",
  due: "Due",
  balance: "Balance",
  statuses: { unpaid: "Unpaid", partial: "Part paid", paid: "Paid" } satisfies Record<FeeStatus, string>,
  overdue: "The balance is past its due date.",
  admissionShort: "Less has been received than the amount due at admission:",
  editAgreement: "Change the agreed fee",
  agreementHint:
    "This is what THIS student agreed to pay. It was captured when they joined and is not affected by later changes to the course fee. Changing it needs a reason, and the change is recorded in the audit log.",
  agreedFeeTotal: "Agreed total fee",
  agreedAdmissionAmount: "Due at admission",
  agreedBalanceDueOn: "Balance due on",
  agreementReason: "Reason for the change",
  saveAgreement: "Save the agreement",
  noLedger: "Fee terms not entered yet.",
  history: "Payment history",
  receipt: "Receipt",
  methods: { cash: "Cash", upi: "UPI received", bank: "Bank transfer", other: "Other" } satisfies Record<FeeMethod, string>,
  viewOnly: "You can view fee status. Recording money requires Fees manage permission.",
  success: { saved: "Fee entry recorded.", agreementSaved: "The agreed fee has been updated." },
  errors: {
    denied: "You do not have permission for this action.",
    invalid: "Check the fee amounts and try again.",
    missing: "That enrollment could not be found.",
    overpaid: "Received amount would be more than the agreed net fee. Check the amounts first.",
    belowReceived: "The agreed total cannot be less than the money already received.",
    agreementMissing: "Set the agreed fee for this student first, then record the payment.",
    discountDecrease: "A recorded discount cannot be reduced from a new receipt. Use the audited agreement change if the student’s terms need correcting.",
    generic: "Could not save the fee entry right now. Please try again."
  }
});

const gu = () => ({
  title: "Fees",
  lede: "કેટલી fee નક્કી થઈ, કેટલી રકમ મળી અને કેટલી બાકી છે — તેનો સરળ offline ledger. અહીં online payment લેવાતું નથી.",
  search: "Student શોધો",
  searchPlaceholder: "નામ, admission no. કે mobile",
  all: "બધા",
  pendingOnly: "ફક્ત બાકી",
  show: "બતાવો",
  filterStatus: "Students બતાવો",
  filterAll: "બધા",
  filterPending: "Fees બાકી",
  filterOverdue: "તારીખ વીતી ગઈ",
  filterPaid: "પૂરી ભરાઈ",
  overdueCount: "Overdue students",
  totalAgreed: "Net fees",
  totalReceived: "મળેલ રકમ",
  totalPending: "બાકી",
  empty: "આ viewમાં કોઈ enrollment નથી.",
  courseFee: "નક્કી થયેલી Course fee",
  discount: "Discount",
  receivedNow: "હમણાં મળેલ રકમ",
  method: "કઈ રીતે મળ્યું",
  receiptNo: "Receipt no. (optional)",
  dueDate: "આગળની due date",
  notes: "Fees note",
  recordPayment: "Payment નોંધો",
  paymentHint: "આજે જેટલી રકમ મળી છે એટલી જ નાખો. Studentની નક્કી થયેલી fee બદલાશે નહીં.",
  moreOptions: "વધુ options",
  discountTotal: "કુલ discount / concession",
  discountHint: "હાલનું amount એમ જ રાખો, additional concession આપવું હોય ત્યારે જ વધારો. નોંધાયેલ discount નવી receiptથી ઓછું થતું નથી.",
  agreementNeeded: "Payment નોંધતા પહેલા આ studentની નક્કી થયેલી fee set કરો.",
  openLedger: "Full fees ledger ખોલો",
  admissionSetupTitle: "આ admissionની fees",
  admissionSetupHint: "આ studentની fee agreement અહીં set કરો અને આજે રકમ મળી હોય તો payment પણ નોંધો. Course default વાપરવું હોય તો agreement fields blank રાખો.",
  courseDefaultNote: "Course defaults available હોય તો અહીં દેખાય છે. અહીં કરેલો ફેરફાર ફક્ત આ student માટે છે.",
  save: "Payment નોંધો",
  saving: "Save થઈ રહ્યું છે…",
  paid: "મળ્યું",
  due: "બાકી",
  balance: "બાકી",
  statuses: { unpaid: "ભરેલી નથી", partial: "થોડી ભરાઈ", paid: "પૂરી ભરાઈ" } satisfies Record<FeeStatus, string>,
  overdue: "બાકી રકમની તારીખ વીતી ગઈ છે.",
  admissionShort: "એડમિશન વખતે ભરવાની રકમ કરતાં ઓછું મળ્યું છે:",
  editAgreement: "નક્કી થયેલી fee બદલો",
  agreementHint:
    "આ student એ જે fee ભરવાનું નક્કી કર્યું હતું એ. જોડાયા ત્યારે નોંધાઈ હતી, અને પછી course ની fee બદલાય તો પણ આ બદલાતી નથી. બદલવા માટે કારણ જરૂરી છે, અને ફેરફાર audit log માં નોંધાય છે.",
  agreedFeeTotal: "નક્કી થયેલી કુલ fee",
  agreedAdmissionAmount: "એડમિશન વખતે ભરવાની",
  agreedBalanceDueOn: "બાકી રકમની તારીખ",
  agreementReason: "ફેરફારનું કારણ",
  saveAgreement: "Agreement સાચવો",
  noLedger: "Feesની માહિતી હજી નાખેલી નથી.",
  history: "Payment history",
  receipt: "Receipt",
  methods: { cash: "Cash", upi: "UPI મળ્યું", bank: "Bank transfer", other: "Other" } satisfies Record<FeeMethod, string>,
  viewOnly: "તમે fees status જોઈ શકો છો. રકમ નોંધવા Fees manage permission જોઈએ.",
  success: { saved: "Fee entry record થઈ ગઈ.", agreementSaved: "નક્કી થયેલી fee અપડેટ થઈ ગઈ." },
  errors: {
    denied: "આ કામ કરવાની permission નથી.",
    invalid: "Fee amounts ચેક કરીને ફરી try કરો.",
    missing: "આ enrollment મળ્યું નથી.",
    overpaid: "મળેલ રકમ net fee કરતાં વધારે થઈ જાય છે. Amounts ચેક કરો.",
    belowReceived: "નક્કી થયેલી કુલ રકમ, અત્યાર સુધી મળેલી રકમ કરતાં ઓછી ન હોઈ શકે.",
    agreementMissing: "પહેલા આ studentની નક્કી થયેલી fee set કરો, પછી payment નોંધો.",
    discountDecrease: "નોંધાયેલ discount નવી receiptથી ઓછું કરી શકાતું નથી. Terms સુધારવા audited agreement change વાપરો.",
    generic: "હમણાં fee entry save થઈ શકી નથી. ફરી try કરો."
  }
});

export function feesCopy(locale: "en" | "gu"): FeesCopy { return locale === "gu" ? gu() : en(); }
