export type PrintCopy = ReturnType<typeof en>;

const en = () => ({
  print: "Print / Save as PDF",
  back: "Back",
  a4Note: "Designed for A4. Use your browser's print dialog and keep the scale at 100%.",

  admissionForm: "Admission form",
  blankForm: "Blank admission form",
  studentSummary: "Student record",
  feeReceipt: "Fee receipt",
  feeStatement: "Fee statement",
  roster: "Batch student list",
  register: "Attendance register",
  brief: "Design brief",
  certificate: "Certificate of completion",

  student: "Student details",
  studentName: "Student name",
  fatherName: "Father's name",
  studentMobile: "Student mobile",
  whatsapp: "WhatsApp",
  email: "Email",
  area: "Area",
  ageBand: "Age",
  admissionNo: "Admission no.",
  admissionDate: "Admission date",
  language: "Language",

  guardian: "Parent / guardian",
  guardianName: "Parent / guardian name",
  guardianPhone: "Parent / guardian mobile",
  guardianRelation: "Relation",

  reference: "Reference",
  referenceName: "Reference name",
  referencePhone: "Reference mobile",

  course: "Course",
  courseName: "Course",
  duration: "Duration",
  months: "months",
  software: "Software",
  batch: "Batch",
  batchTiming: "Batch timing",
  joiningDate: "Joining date",
  demo: "Free demo",
  demoDone: "Demo completed on",

  whatWeTeach: "What is taught",
  practical: "Practical training",

  fees: "Fee agreement",
  feeTotal: "Total course fees",
  feeAdmission: "Received at admission",
  feeBalance: "Remaining",
  feeDueOn: "Balance due on",
  feeReceived: "Received",
  feeMethod: "Received by",
  receiptNo: "Receipt no.",
  feeStatus: "Status",
  feeDate: "Date",
  feeNotes: "Note",
  runningBalance: "Balance",
  noFees: "No fee entries recorded yet.",
  offlineNote:
    "Fees are received at the studio. This receipt is issued for a payment already made; no payment is taken on the website.",

  norms: "Admission norms",
  declaration: "Student declaration",
  studentSignature: "Student signature",
  parentSignature: "Parent signature",
  trainerSignature: "Trainer signature",
  officeStamp: "Office stamp",
  date: "Date",

  rollNo: "No.",
  seats: "Seats",
  trainer: "Trainer",
  days: "Days",
  status: "Status",
  attendanceNote:
    "Mark P for present, A for absent, L for late. Sign at the end of each session.",
  registerFor: "Register for",
  signature: "Signature",

  company: "Company",
  contact: "Contact",
  productType: "Product type",
  technique: "Technique",
  dimensions: "Dimensions",
  quantity: "Quantity",
  colourCount: "Colours",
  fileFormat: "File format",
  deadline: "Deadline",
  details: "Details",

  verifyAt: "Verify this certificate at",
  revoked: "REVOKED — this certificate is no longer valid.",
  issuedOn: "Issued on",
  grade: "Result / grade",
  notRecorded: "—"
});

const gu = (): PrintCopy => ({
  print: "Print / PDF સાચવો",
  back: "પાછા",
  a4Note: "A4 માટે બનાવેલું છે. Browser ના print dialog માં scale 100% રાખો.",

  admissionForm: "એડમિશન ફોર્મ",
  blankForm: "કોરું એડમિશન ફોર્મ",
  studentSummary: "Student રેકોર્ડ",
  feeReceipt: "Fee રસીદ",
  feeStatement: "Fee સ્ટેટમેન્ટ",
  roster: "બેચ સ્ટુડન્ટ લિસ્ટ",
  register: "હાજરી રજિસ્ટર",
  brief: "ડિઝાઇન બ્રીફ",
  certificate: "કોર્સ પૂર્ણતાનું પ્રમાણપત્ર",

  student: "Student ની વિગત",
  studentName: "Student નું નામ",
  fatherName: "પિતાનું નામ",
  studentMobile: "Student નો મોબાઇલ",
  whatsapp: "WhatsApp",
  email: "Email",
  area: "વિસ્તાર",
  ageBand: "ઉંમર",
  admissionNo: "એડમિશન નં.",
  admissionDate: "એડમિશન તારીખ",
  language: "ભાષા",

  guardian: "માતા-પિતા / વાલી",
  guardianName: "માતા-પિતા / વાલીનું નામ",
  guardianPhone: "માતા-પિતા / વાલીનો મોબાઇલ",
  guardianRelation: "સંબંધ",

  reference: "રેફરન્સ",
  referenceName: "રેફરન્સનું નામ",
  referencePhone: "રેફરન્સનો મોબાઇલ",

  course: "કોર્સ",
  courseName: "કોર્સ",
  duration: "ડ્યુરેશન",
  months: "મહિના",
  software: "સોફ્ટવેર",
  batch: "બેચ",
  batchTiming: "બેચનો સમય",
  joiningDate: "જોડાયાની તારીખ",
  demo: "ફ્રી ડેમો",
  demoDone: "ડેમો પૂરો થયો",

  whatWeTeach: "શું શીખવાય છે",
  practical: "પ્રેક્ટિકલ ટ્રેનિંગ",

  fees: "Fee કરાર",
  feeTotal: "કુલ કોર્સ ફી",
  feeAdmission: "એડમિશન વખતે મળેલી",
  feeBalance: "બાકી",
  feeDueOn: "બાકી રકમની તારીખ",
  feeReceived: "મળેલી રકમ",
  feeMethod: "કઈ રીતે મળી",
  receiptNo: "રસીદ નં.",
  feeStatus: "સ્થિતિ",
  feeDate: "તારીખ",
  feeNotes: "નોંધ",
  runningBalance: "બાકી",
  noFees: "હજી કોઈ fee entry નોંધાઈ નથી.",
  offlineNote:
    "Fee સ્ટુડિયો પર મળે છે. આ રસીદ પહેલેથી ભરાયેલા પેમેન્ટ માટે છે; વેબસાઇટ પર કોઈ પેમેન્ટ લેવાતું નથી.",

  norms: "એડમિશન નિયમો",
  declaration: "વિદ્યાર્થીનું ડિક્લેરેશન",
  studentSignature: "વિદ્યાર્થીની સહી",
  parentSignature: "વાલીની સહી",
  trainerSignature: "ટ્રેનરની સહી",
  officeStamp: "ઓફિસ સ્ટેમ્પ",
  date: "તારીખ",

  rollNo: "નં.",
  seats: "સીટ",
  trainer: "ટ્રેનર",
  days: "દિવસ",
  status: "સ્થિતિ",
  attendanceNote:
    "હાજર માટે P, ગેરહાજર માટે A, મોડા આવે તો L લખો. દરેક સેશનના અંતે સહી કરો.",
  registerFor: "રજિસ્ટર",
  signature: "સહી",

  company: "કંપની",
  contact: "સંપર્ક",
  productType: "પ્રોડક્ટ પ્રકાર",
  technique: "ટેકનિક",
  dimensions: "માપ",
  quantity: "જથ્થો",
  colourCount: "કલર",
  fileFormat: "ફાઇલ ફોર્મેટ",
  deadline: "ડેડલાઇન",
  details: "વિગત",

  verifyAt: "આ પ્રમાણપત્ર અહીં ચકાસો",
  revoked: "REVOKED — આ પ્રમાણપત્ર હવે માન્ય નથી.",
  issuedOn: "આપવાની તારીખ",
  grade: "પરિણામ / ગ્રેડ",
  notRecorded: "—"
});

export function printCopy(locale: "en" | "gu"): PrintCopy {
  return locale === "gu" ? gu() : en();
}
