import type { EnrollmentStatus } from "./students";

export type StudentsCopy = ReturnType<typeof en>;

const en = () => ({
  title: "Students",
  lede: "One place for every learner: admission details, batch, attendance, fees and certificates.",
  quickTitle: "Front desk",
  directAdmission: "Direct admission",
  directAdmissionHint: "For a walk-in, phone or WhatsApp student who is joining now. No website form is needed.",
  convertEnquiry: "Convert enquiry to student",
  convertEnquiryHint: "Use this when an Admissions enquiry has decided to join. Their details are carried forward.",
  addEnrollment: "Add another course / batch",
  editStudent: "Update student details",
  directory: "Student list",
  search: "Search student",
  searchPlaceholder: "Name, admission no. or mobile",
  all: "All students",
  empty: "No students yet. Use Direct admission when the first student joins.",
  selectStudent: "Select a student to see the full record.",
  admissionNo: "Admission no.",
  fullName: "Student name",
  phone: "Mobile",
  whatsapp: "WhatsApp",
  email: "Email (optional)",
  area: "Area / locality",
  language: "Preferred language",
  languageGu: "Gujarati",
  languageEn: "English",
  minor: "Under 18",
  photoConsent: "Photo / work sharing consent received",
  notes: "Internal note",
  guardian: "Parent / guardian",
  guardianName: "Guardian name",
  guardianPhone: "Guardian mobile",
  guardianRelation: "Relation",
  batch: "Batch",
  course: "Course",
  joinedOn: "Joined on",
  status: "Enrollment status",
  completedOn: "Completed on",
  enrollments: "Courses & batches",
  attendance: "Attendance",
  fees: "Fees",
  certificates: "Certificates",
  totalClasses: "Classes marked",
  attendanceRate: "Present / late rate",
  paid: "Received",
  due: "Balance",
  noFees: "Fee details not entered yet.",
  noCertificates: "No certificate issued yet.",
  noEnrollments: "No batch enrollment yet.",
  selectBatch: "Choose batch",
  selectEnquiry: "Choose enquiry",
  choose: "Choose…",
  save: "Save",
  saving: "Saving…",
  createAdmission: "Create admission",
  converting: "Creating student…",
  convert: "Create student & enroll",
  enroll: "Add enrollment",
  updateEnrollment: "Update enrollment",
  viewOnly: "You can view student records. Editing requires Students manage permission.",
  seatUnavailable: "That batch has no available seat or is not open for enrollment.",
  statuses: {
    applied: "Applied",
    active: "Learning",
    completed: "Completed",
    dropped: "Stopped"
  } satisfies Record<EnrollmentStatus, string>,
  success: {
    studentCreated: "Student admitted and added to the batch.",
    studentUpdated: "Student details updated.",
    converted: "Enquiry converted to a student and batch enrollment.",
    enrolled: "Enrollment added.",
    enrollmentUpdated: "Enrollment updated."
  },
  errors: {
    denied: "You do not have permission for this action.",
    invalid: "Please check the highlighted details and try again.",
    missing: "That student, enquiry or batch could not be found.",
    duplicate: "This student is already enrolled in that batch.",
    seat: "That batch is full or not available for new enrollment.",
    alreadyConverted: "That enquiry is already enrolled.",
    generic: "Could not save this right now. Please try again."
  }
});

const gu = () => ({
  title: "સ્ટુડન્ટ્સ",
  lede: "દરેક સ્ટુડન્ટની એક જ જગ્યાએ સંપૂર્ણ માહિતી — admission, batch, હાજરી, fees અને certificate.",
  quickTitle: "Front desk",
  directAdmission: "સીધું Admission",
  directAdmissionHint: "Walk-in, phone કે WhatsApp પરથી સીધા જોડાતા સ્ટુડન્ટ માટે. Website form આવવું જરૂરી નથી.",
  convertEnquiry: "Enquiryમાંથી Student બનાવો",
  convertEnquiryHint: "Admissionsમાં enquiry કરેલા વ્યક્તિએ join કરવાનું નક્કી કર્યું હોય ત્યારે. તેમની માહિતી આપમેળે આગળ આવે છે.",
  addEnrollment: "બીજો Course / Batch ઉમેરો",
  editStudent: "Studentની માહિતી સુધારો",
  directory: "Student list",
  search: "Student શોધો",
  searchPlaceholder: "નામ, admission no. કે mobile",
  all: "બધા Students",
  empty: "હજુ કોઈ student નથી. પહેલો student જોડાય ત્યારે સીધું Admission વાપરો.",
  selectStudent: "સંપૂર્ણ record જોવા student પસંદ કરો.",
  admissionNo: "Admission no.",
  fullName: "Studentનું નામ",
  phone: "Mobile",
  whatsapp: "WhatsApp",
  email: "Email (optional)",
  area: "Area / locality",
  language: "પસંદની ભાષા",
  languageGu: "ગુજરાતી",
  languageEn: "English",
  minor: "18 વર્ષથી નાનો/નાની",
  photoConsent: "Photo / work share કરવાની મંજૂરી મળી છે",
  notes: "Staff માટે note",
  guardian: "Parent / Guardian",
  guardianName: "Guardianનું નામ",
  guardianPhone: "Guardian mobile",
  guardianRelation: "સંબંધ",
  batch: "Batch",
  course: "Course",
  joinedOn: "Join date",
  status: "Enrollment status",
  completedOn: "Complete date",
  enrollments: "Courses & Batches",
  attendance: "હાજરી",
  fees: "Fees",
  certificates: "Certificates",
  totalClasses: "માર્ક થયેલા classes",
  attendanceRate: "Present / late %",
  paid: "મળેલ રકમ",
  due: "બાકી",
  noFees: "Feesની માહિતી હજી નાખેલી નથી.",
  noCertificates: "હજુ certificate issue થયેલું નથી.",
  noEnrollments: "હજુ batch enrollment નથી.",
  selectBatch: "Batch પસંદ કરો",
  selectEnquiry: "Enquiry પસંદ કરો",
  choose: "પસંદ કરો…",
  save: "Save",
  saving: "Save થઈ રહ્યું છે…",
  createAdmission: "Admission બનાવો",
  converting: "Student બની રહ્યો છે…",
  convert: "Student બનાવો અને Batchમાં ઉમેરો",
  enroll: "Enrollment ઉમેરો",
  updateEnrollment: "Enrollment સુધારો",
  viewOnly: "તમે student record જોઈ શકો છો. ફેરફાર માટે Students manage permission જોઈએ.",
  seatUnavailable: "આ batchમાં seat ખાલી નથી અથવા નવું enrollment લઈ શકાતું નથી.",
  statuses: {
    applied: "Applied",
    active: "ચાલુ છે",
    completed: "Complete",
    dropped: "બંધ કર્યું"
  } satisfies Record<EnrollmentStatus, string>,
  success: {
    studentCreated: "Studentનું admission થઈ ગયું અને batchમાં ઉમેરાયો.",
    studentUpdated: "Studentની માહિતી update થઈ ગઈ.",
    converted: "Enquiryમાંથી student બનાવી batchમાં enrollment થઈ ગયું.",
    enrolled: "Enrollment ઉમેરાઈ ગયું.",
    enrollmentUpdated: "Enrollment update થઈ ગયું."
  },
  errors: {
    denied: "આ કામ કરવાની permission નથી.",
    invalid: "માહિતી ચેક કરીને ફરી try કરો.",
    missing: "આ student, enquiry કે batch મળ્યો નથી.",
    duplicate: "આ student પહેલેથી આ batchમાં છે.",
    seat: "આ batch full છે અથવા નવું enrollment લઈ શકાતું નથી.",
    alreadyConverted: "આ enquiryનું enrollment પહેલેથી થઈ ગયું છે.",
    generic: "હમણાં save થઈ શક્યું નથી. ફરી try કરો."
  }
});

export function studentsCopy(locale: "en" | "gu"): StudentsCopy {
  return locale === "gu" ? gu() : en();
}
